name: auto-release

on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        name: Downloading Repository

      - uses: actions/setup-node@v1
        name: Use Node.js
        with:
          node-version: '12.x'
      - name: Run semantic-release
        run: npx semantic-release@17.*